# Generated by Django 5.0.2 on 2024-06-24 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('user_message', models.TextField()),
                ('chatbot_response', models.TextField()),
                ('for_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromChat', to='ai.chat')),
            ],
        ),
    ]
