# Generated by Django 5.0.2 on 2024-06-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_history',
            name='date_created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date_created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
