# Generated by Django 5.0.2 on 2024-07-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_chat_history_date_created_alter_chat_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.UUIDField(null=True),
        ),
    ]
