# Generated by Django 5.0.2 on 2024-07-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_chat_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_msg', models.TextField()),
                ('model_msg', models.TextField()),
            ],
        ),
    ]
