# Generated by Django 4.2.3 on 2024-10-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_model_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_parameters',
            name='model_msg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='model_parameters',
            name='user_msg',
            field=models.TextField(null=True),
        ),
    ]
