# Generated by Django 4.2.3 on 2024-08-05 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFinancialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField(null=True)),
                ('recurring_deposit_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('recurring_deposit_frequency', models.CharField(choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Month')], default=None, max_length=5, null=True)),
                ('last_recurring_deposit', models.DateTimeField(null=True)),
                ('next_recurring_deposit', models.DateTimeField(null=True)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='UsersStock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
