# Generated by Django 5.0.2 on 2024-06-29 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.TextField()),
                ('bank_routing_number', models.TextField()),
                ('bank_account_number', models.TextField()),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_balance', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='externalBankAccount', to='bank.externalbankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEP', 'Deposit'), ('WTH', 'Withdrawal')], default=None, max_length=3, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_executed', models.DateTimeField(null=True)),
                ('for_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account', to='bank.cashaccount')),
            ],
        ),
    ]
