# Generated by Django 4.2.3 on 2024-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('state', models.TextField()),
                ('zipCode', models.TextField()),
                ('city', models.TextField()),
                ('ssn', models.TextField()),
                ('dob', models.TextField()),
                ('ip_address', models.TextField()),
            ],
        ),
    ]
