# Generated by Django 4.2.3 on 2024-07-12 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0003_cashaccount_customer_id_kyc_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='for_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='knowingCustomer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kyc',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
