# Generated by Django 4.2.3 on 2024-07-14 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_kyc_documents_submitted_kyc_documents_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='externalBankAccount', to='bank.externalbankaccount'),
        ),
    ]
