# Generated by Django 4.2.3 on 2024-07-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_externalbankaccount_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalbankaccount',
            name='ach_authorized',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='externalbankaccount',
            name='processor_token',
            field=models.TextField(null=True),
        ),
    ]
